version: '2'
services:
  threedshop-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/threedshop/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=threedshop
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
